// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface SiteConfig {
  /**
   * Folder where articles are stored
   */
  parentId: string;

  /**
   * Publisher id
   */
  publisher: string;

  /**
   * Channels
   */
  channels: string;
}
