// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type NtbArticle = import("./ntb-article").NtbArticle;

declare global {
  namespace XP {
    interface ContentTypes {
      "no.item.ntb:ntb-article": NtbArticle;
    }
  }
}
