// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface NtbArticle {
  /**
   * Title
   */
  title: string;

  /**
   * Lead text
   */
  leadtext: string;

  /**
   * Article text
   */
  body: string;

  /**
   * Main image
   */
  imageId?: string;

  /**
   * Images
   */
  images?: Array<string>;

  /**
   * Links
   */
  links?: Array<{
    /**
     * Url
     */
    url: string;

    /**
     * Description
     */
    description: string;
  }>;

  /**
   * Keywords
   */
  keywords?: Array<string>;

  /**
   * NTB id
   */
  ntbId: number;

  /**
   * Published
   */
  published: string;

  /**
   * NTB url
   */
  url: string;

  /**
   * Type
   */
  type: string;

  /**
   * NTB publisher id
   */
  publisherId: number;

  /**
   * NTB channel id
   */
  channelId: number;

  /**
   * Language
   */
  language: string;
}
